project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  site-url: https://g-bez.github.io/my-portfolio/
  
  cookie-consent: 
    type: express
    style: headline
    palette: dark
  google-analytics:
    tracking-id: "G-TVL122T9T3"
    anonymize-ip: true
  
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/G-Bez
      - icon: rss
        href: index.xml
    left: 
      - text: About me
        href: about.qmd

format:
  html:
    code-copy: true
    code-overflow: wrap
    theme: darkly
    css: styles.css
    fontsize: 0.9em

editor: visual
