project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://g-bez.github.io/my-portfolio/
  open-graph:
    image: opengraph_thumbnail.png
    title: "My blog about Data Analysis"
    description: "Short posts about data analysis, related tools and methods."
  
  cookie-consent:
    type: express
    style: headline
    palette: dark
  # google-analytics:
  #   tracking-id: "G-W0YC9G1MJG"
  #   anonymize-ip: true
  
  navbar:
    pinned: true
    right:
      - text: Archive
        href: archive.qmd
      - icon: github
        href: https://github.com/G-Bez
      - icon: rss
        href: index.xml
    left: 
      - text: About me
        href: about.qmd

format:
  html:
    include-in-header: head_tag.js
    include-before-body: body_tag.js
    code-copy: true
    code-overflow: wrap
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    fontsize: 0.9em

editor: visual
