project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/G-Bez
    left: 
      - text: About me
        href: about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    fontsize: 0.9em

editor: visual

