{
  "hash": "cdb2c903aa25e05d3f1025d3cc2e6bb1",
  "result": {
    "markdown": "---\ntitle: \"Linear regression diagnostics in R with lindia package\"\ndate: \"2022-11-17\"\ncategories: [R, Regression]\nimage: regression_thumbnail.png\nformat:\n  html:\n    code-tools: true\n    df-print: paged\n    fontsize: 0.9em\n    include-in-header: navbar.html\n    css: theme.css\n    toc: true\ncomments: \n    utterances: \n      repo:  G-Bez/my-portfolio \n      theme: photon-dark\ntitle-block-banner: false\neditor: visual\n---\n\n::: {.cell}\n<style type=\"text/css\">\n.justify {\n  text-align: justify !important\n}\n</style>\n:::\n\n\n::: justify\nRegression diagnostics is the part of regression analysis whose objective is to investigate if the calculated model and the assumptions we made about the data and the model, are consistent with the recorded data. These diagnostics include graphical and numerical tools for checking the adequacy of the assumptions with respect to both the data and the form of the model. Here I'll provide some examples of graphical disgnostics in R with [`lindia`](https://github.com/yeukyul/lindia) package. `lindia` is an extention to [`ggplot2`](http://ggplot2.org) to provide streamlined plotting features of linear model diagnostic plots.\n:::\n\n## Linear models assumptions\n\n::: justify\nWe start with a quick recap of **OLS linear regression models** **assumptions**. Linear models make a number of assumptions about the predictor variables, the response variables and their relationship. Numerous extensions have been developed that allow each of these assumptions to be relaxed (i.e. reduced to a weaker form), and in some cases eliminated entirely. Generally these extensions make the estimation procedure more complex and time-consuming, and may also require more data in order to produce an equally precise model. The following are the major assumptions made by standard linear regression models with standard estimation techniques (e.g. ordinary least squares):\n\n-   **Linearity**: the basic assumption of the linear regression model, as the name suggests, is that of a linear relationship between the dependent and independent variables.\n\n    $y_i = \\beta_1x_{1i}+ \\beta_2x_{2i} + ...+\\beta_nx_{ni} + \\epsilon_i$\n\n    Here the linearity is only with respect to the parameters. Oddly enough, there's no such restriction on the degree or form of the explanatory variables themselves. Those can be transforned as you like, for example taking the square or logarithm of one or more predictors; polynomials are also allowed.\n\n-   **Null population mean of error terms**: the error term accounts for the variation in the dependent variable that the independent variables do not explain. Random chance should determine the values of the error term. For your model to be unbiased, the average value of the error term must equal zero.\n\n-   **Predictors uncorrelated with residuals**: if an independent variable is correlated with the error term, we can use the independent variable to predict the error term, which violates the notion that the error term represents unpredictable random error. This assumption is also referred to as exogeneity. When this type of correlation exists, there is endogeneity. Violations of this assumption can occur because there is simultaneity between the independent and dependent variables, omitted variable bias, or measurement error in the independent variables.\n\n-   **No autocorrelation of residuals**: the residuals in the linear regression model are assumed to be independently and identically distributed (i.i.d.). This implies that each error term is independent and unrelated to the other error terms. So, knowing one error term tells us nothing about the other(s). Also, all errors have the same distribution, the normal distribution (with zero mean and finite variance). The error term at a particular point in time should have no correlation with any of the past values. This makes the error terms equivalent to random noise that cannot be predicted. In the case of correlation between the residuals, the model's accuracy is affected. Autocorrelation or serial correlation is a problem **specific to regressions involving time-series**.\n\n-   **No multicollinearity**: the independent variables should not be correlated with each other. If there is a linear relationship between one or more explanatory variables, it adds to the complexity of the model without being able to delineate the impact of each explanatory variable on the response variable.\n\n-   **Normality of residuals**: the classic linear regression model assumes that the error term is normally distributed. If this assumption is violated, it is not a big problem, especially if we have a large number of observations. This is because the central limit theorem will apply if we have a large number of observations, implying that the sampling distribution will resemble normality irrespective of the parent distribution for large sample sizes. However, if the number of observations is small and the normality assumption is violated, the standard errors in your model's output will be unreliable.\n\n-   **Homoskedasticity**: an important assumption of linear regression is that the error terms have the same variance across all observations. Unequal variance in the error terms is called heteroskedasticity and may be caused due to many reasons like the presence of outliers, or an incorrectly specified model. If we run the regression with heteroskedasticity present, the standard errors would be large and the model would have unreliable predictions.\n:::\n\n## Install lindia\n\n::: justify\nYou can install `lindia` from CRAN repository with:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"lindia\")\n```\n:::\n\n\n::: justify\nOr the developer version from GitHub:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndevtools::install_github(\"yeukyul/lindia\")\n```\n:::\n\n\n## Packages\n\n::: justify\nWe start by loading the needed packages.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lindia)\nlibrary(car)\nlibrary(ggplot2)\nlibrary(patchwork)\nlibrary(olsrr)\nlibrary(corrplot)\n```\n:::\n\n\n## Dataset\n\n::: justify\nWe'll build a linear model on `swiss` R prebuilt dataset.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswiss <- datasets::swiss\nswiss\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Fertility\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Agriculture\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Examination\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Education\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Catholic\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Infant.Mortality\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"80.2\",\"2\":\"17.0\",\"3\":\"15\",\"4\":\"12\",\"5\":\"9.96\",\"6\":\"22.2\",\"_rn_\":\"Courtelary\"},{\"1\":\"83.1\",\"2\":\"45.1\",\"3\":\"6\",\"4\":\"9\",\"5\":\"84.84\",\"6\":\"22.2\",\"_rn_\":\"Delemont\"},{\"1\":\"92.5\",\"2\":\"39.7\",\"3\":\"5\",\"4\":\"5\",\"5\":\"93.40\",\"6\":\"20.2\",\"_rn_\":\"Franches-Mnt\"},{\"1\":\"85.8\",\"2\":\"36.5\",\"3\":\"12\",\"4\":\"7\",\"5\":\"33.77\",\"6\":\"20.3\",\"_rn_\":\"Moutier\"},{\"1\":\"76.9\",\"2\":\"43.5\",\"3\":\"17\",\"4\":\"15\",\"5\":\"5.16\",\"6\":\"20.6\",\"_rn_\":\"Neuveville\"},{\"1\":\"76.1\",\"2\":\"35.3\",\"3\":\"9\",\"4\":\"7\",\"5\":\"90.57\",\"6\":\"26.6\",\"_rn_\":\"Porrentruy\"},{\"1\":\"83.8\",\"2\":\"70.2\",\"3\":\"16\",\"4\":\"7\",\"5\":\"92.85\",\"6\":\"23.6\",\"_rn_\":\"Broye\"},{\"1\":\"92.4\",\"2\":\"67.8\",\"3\":\"14\",\"4\":\"8\",\"5\":\"97.16\",\"6\":\"24.9\",\"_rn_\":\"Glane\"},{\"1\":\"82.4\",\"2\":\"53.3\",\"3\":\"12\",\"4\":\"7\",\"5\":\"97.67\",\"6\":\"21.0\",\"_rn_\":\"Gruyere\"},{\"1\":\"82.9\",\"2\":\"45.2\",\"3\":\"16\",\"4\":\"13\",\"5\":\"91.38\",\"6\":\"24.4\",\"_rn_\":\"Sarine\"},{\"1\":\"87.1\",\"2\":\"64.5\",\"3\":\"14\",\"4\":\"6\",\"5\":\"98.61\",\"6\":\"24.5\",\"_rn_\":\"Veveyse\"},{\"1\":\"64.1\",\"2\":\"62.0\",\"3\":\"21\",\"4\":\"12\",\"5\":\"8.52\",\"6\":\"16.5\",\"_rn_\":\"Aigle\"},{\"1\":\"66.9\",\"2\":\"67.5\",\"3\":\"14\",\"4\":\"7\",\"5\":\"2.27\",\"6\":\"19.1\",\"_rn_\":\"Aubonne\"},{\"1\":\"68.9\",\"2\":\"60.7\",\"3\":\"19\",\"4\":\"12\",\"5\":\"4.43\",\"6\":\"22.7\",\"_rn_\":\"Avenches\"},{\"1\":\"61.7\",\"2\":\"69.3\",\"3\":\"22\",\"4\":\"5\",\"5\":\"2.82\",\"6\":\"18.7\",\"_rn_\":\"Cossonay\"},{\"1\":\"68.3\",\"2\":\"72.6\",\"3\":\"18\",\"4\":\"2\",\"5\":\"24.20\",\"6\":\"21.2\",\"_rn_\":\"Echallens\"},{\"1\":\"71.7\",\"2\":\"34.0\",\"3\":\"17\",\"4\":\"8\",\"5\":\"3.30\",\"6\":\"20.0\",\"_rn_\":\"Grandson\"},{\"1\":\"55.7\",\"2\":\"19.4\",\"3\":\"26\",\"4\":\"28\",\"5\":\"12.11\",\"6\":\"20.2\",\"_rn_\":\"Lausanne\"},{\"1\":\"54.3\",\"2\":\"15.2\",\"3\":\"31\",\"4\":\"20\",\"5\":\"2.15\",\"6\":\"10.8\",\"_rn_\":\"La Vallee\"},{\"1\":\"65.1\",\"2\":\"73.0\",\"3\":\"19\",\"4\":\"9\",\"5\":\"2.84\",\"6\":\"20.0\",\"_rn_\":\"Lavaux\"},{\"1\":\"65.5\",\"2\":\"59.8\",\"3\":\"22\",\"4\":\"10\",\"5\":\"5.23\",\"6\":\"18.0\",\"_rn_\":\"Morges\"},{\"1\":\"65.0\",\"2\":\"55.1\",\"3\":\"14\",\"4\":\"3\",\"5\":\"4.52\",\"6\":\"22.4\",\"_rn_\":\"Moudon\"},{\"1\":\"56.6\",\"2\":\"50.9\",\"3\":\"22\",\"4\":\"12\",\"5\":\"15.14\",\"6\":\"16.7\",\"_rn_\":\"Nyone\"},{\"1\":\"57.4\",\"2\":\"54.1\",\"3\":\"20\",\"4\":\"6\",\"5\":\"4.20\",\"6\":\"15.3\",\"_rn_\":\"Orbe\"},{\"1\":\"72.5\",\"2\":\"71.2\",\"3\":\"12\",\"4\":\"1\",\"5\":\"2.40\",\"6\":\"21.0\",\"_rn_\":\"Oron\"},{\"1\":\"74.2\",\"2\":\"58.1\",\"3\":\"14\",\"4\":\"8\",\"5\":\"5.23\",\"6\":\"23.8\",\"_rn_\":\"Payerne\"},{\"1\":\"72.0\",\"2\":\"63.5\",\"3\":\"6\",\"4\":\"3\",\"5\":\"2.56\",\"6\":\"18.0\",\"_rn_\":\"Paysd'enhaut\"},{\"1\":\"60.5\",\"2\":\"60.8\",\"3\":\"16\",\"4\":\"10\",\"5\":\"7.72\",\"6\":\"16.3\",\"_rn_\":\"Rolle\"},{\"1\":\"58.3\",\"2\":\"26.8\",\"3\":\"25\",\"4\":\"19\",\"5\":\"18.46\",\"6\":\"20.9\",\"_rn_\":\"Vevey\"},{\"1\":\"65.4\",\"2\":\"49.5\",\"3\":\"15\",\"4\":\"8\",\"5\":\"6.10\",\"6\":\"22.5\",\"_rn_\":\"Yverdon\"},{\"1\":\"75.5\",\"2\":\"85.9\",\"3\":\"3\",\"4\":\"2\",\"5\":\"99.71\",\"6\":\"15.1\",\"_rn_\":\"Conthey\"},{\"1\":\"69.3\",\"2\":\"84.9\",\"3\":\"7\",\"4\":\"6\",\"5\":\"99.68\",\"6\":\"19.8\",\"_rn_\":\"Entremont\"},{\"1\":\"77.3\",\"2\":\"89.7\",\"3\":\"5\",\"4\":\"2\",\"5\":\"100.00\",\"6\":\"18.3\",\"_rn_\":\"Herens\"},{\"1\":\"70.5\",\"2\":\"78.2\",\"3\":\"12\",\"4\":\"6\",\"5\":\"98.96\",\"6\":\"19.4\",\"_rn_\":\"Martigwy\"},{\"1\":\"79.4\",\"2\":\"64.9\",\"3\":\"7\",\"4\":\"3\",\"5\":\"98.22\",\"6\":\"20.2\",\"_rn_\":\"Monthey\"},{\"1\":\"65.0\",\"2\":\"75.9\",\"3\":\"9\",\"4\":\"9\",\"5\":\"99.06\",\"6\":\"17.8\",\"_rn_\":\"St Maurice\"},{\"1\":\"92.2\",\"2\":\"84.6\",\"3\":\"3\",\"4\":\"3\",\"5\":\"99.46\",\"6\":\"16.3\",\"_rn_\":\"Sierre\"},{\"1\":\"79.3\",\"2\":\"63.1\",\"3\":\"13\",\"4\":\"13\",\"5\":\"96.83\",\"6\":\"18.1\",\"_rn_\":\"Sion\"},{\"1\":\"70.4\",\"2\":\"38.4\",\"3\":\"26\",\"4\":\"12\",\"5\":\"5.62\",\"6\":\"20.3\",\"_rn_\":\"Boudry\"},{\"1\":\"65.7\",\"2\":\"7.7\",\"3\":\"29\",\"4\":\"11\",\"5\":\"13.79\",\"6\":\"20.5\",\"_rn_\":\"La Chauxdfnd\"},{\"1\":\"72.7\",\"2\":\"16.7\",\"3\":\"22\",\"4\":\"13\",\"5\":\"11.22\",\"6\":\"18.9\",\"_rn_\":\"Le Locle\"},{\"1\":\"64.4\",\"2\":\"17.6\",\"3\":\"35\",\"4\":\"32\",\"5\":\"16.92\",\"6\":\"23.0\",\"_rn_\":\"Neuchatel\"},{\"1\":\"77.6\",\"2\":\"37.6\",\"3\":\"15\",\"4\":\"7\",\"5\":\"4.97\",\"6\":\"20.0\",\"_rn_\":\"Val de Ruz\"},{\"1\":\"67.6\",\"2\":\"18.7\",\"3\":\"25\",\"4\":\"7\",\"5\":\"8.65\",\"6\":\"19.5\",\"_rn_\":\"ValdeTravers\"},{\"1\":\"35.0\",\"2\":\"1.2\",\"3\":\"37\",\"4\":\"53\",\"5\":\"42.34\",\"6\":\"18.0\",\"_rn_\":\"V. De Geneve\"},{\"1\":\"44.7\",\"2\":\"46.6\",\"3\":\"16\",\"4\":\"29\",\"5\":\"50.43\",\"6\":\"18.2\",\"_rn_\":\"Rive Droite\"},{\"1\":\"42.8\",\"2\":\"27.7\",\"3\":\"22\",\"4\":\"29\",\"5\":\"58.33\",\"6\":\"19.3\",\"_rn_\":\"Rive Gauche\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: justify\nThe data frame (47 observations on 6 variables) has standardized fertility measure and socio-economic indicators for each of 47 French-speaking provinces of Switzerland at about 1888. Below a list of its variables:\n\n-   **Fertility**: *I~g~*, 'common standardized fertility measure'.\n-   **Agriculture**: % of males involved in agriculture as occupation.\n-   **Examination**: % draftees receiving highest mark on army examination.\n-   **Education**: % education beyond primary school for draftees.\n-   **Catholic**: % 'catholic' (as opposed to 'protestant').\n-   **Infant.Mortality**: live births who live less than 1 year.\n\nAll variables but 'Fertility' give proportions of the population.\n:::\n\n## Linear model\n\n::: justify\nWe build a linear model with 'Fertility' as dependent variable, and other variables as predictors, with `lm()` function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(formula = Fertility ~ ., data = swiss)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Fertility ~ ., data = swiss)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.2743  -5.2617   0.5032   4.1198  15.3213 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      66.91518   10.70604   6.250 1.91e-07 ***\nAgriculture      -0.17211    0.07030  -2.448  0.01873 *  \nExamination      -0.25801    0.25388  -1.016  0.31546    \nEducation        -0.87094    0.18303  -4.758 2.43e-05 ***\nCatholic          0.10412    0.03526   2.953  0.00519 ** \nInfant.Mortality  1.07705    0.38172   2.822  0.00734 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.165 on 41 degrees of freedom\nMultiple R-squared:  0.7067,\tAdjusted R-squared:  0.671 \nF-statistic: 19.76 on 5 and 41 DF,  p-value: 5.594e-10\n```\n:::\n:::\n\n\n::: justify\nIt seems like a decent model, with a sufficiently high *R^2^* (0.671), and most estimates being statistically significant (with a confidence level of at least 95%), except for 'Examination' variable. So we just drop it and re-build the model.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- lm(formula = Fertility ~ Agriculture + Education + Catholic + Infant.Mortality, data = swiss)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Fertility ~ Agriculture + Education + Catholic + \n    Infant.Mortality, data = swiss)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.6765  -6.0522   0.7514   3.1664  16.1422 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      62.10131    9.60489   6.466 8.49e-08 ***\nAgriculture      -0.15462    0.06819  -2.267  0.02857 *  \nEducation        -0.98026    0.14814  -6.617 5.14e-08 ***\nCatholic          0.12467    0.02889   4.315 9.50e-05 ***\nInfant.Mortality  1.07844    0.38187   2.824  0.00722 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.168 on 42 degrees of freedom\nMultiple R-squared:  0.6993,\tAdjusted R-squared:  0.6707 \nF-statistic: 24.42 on 4 and 42 DF,  p-value: 1.717e-10\n```\n:::\n:::\n\n\n::: justify\nNow, all estimates are statistically significant, with lower standard errors, more narrow confidence intervals, lower p-values and a minimal loss of goodness of fit (*R^2^* = 0.6707). Below we draw the regression plots for each regressor with a custom function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Custom function\"}\nregr_p <- function(Data, x, y) {\n  x = parse(text = x)\n  y = parse(text = y)\n  \n  model_summ <- lm(data = Data, eval(y) ~ eval(x)) |> summary()\n  \n  Sign <- if(model_summ[[\"coefficients\"]][2] >= 0) \"+\" else \"\"\n  Title = paste(\"Regression plot (X=\", x, \")\", sep = \"\")\n  Subtitle = paste(y, \"=\", model_summ[[\"coefficients\"]][1] |> round(2), Sign, \n                   model_summ[[\"coefficients\"]][2] |> round(2), \"*\", x, \"   \", \"\\nr-squared= \",\n                   model_summ[[\"r.squared\"]] |> round(4), \"  Adj.r-squared= \",\n                   model_summ[[\"adj.r.squared\"]] |> round(4))\n  \n  p <- ggplot2::ggplot( data = Data, ggplot2::aes(x = eval(x), y = eval(y)) ) +\n    ggplot2::geom_point() +\n    ggplot2::geom_smooth(method = \"lm\", colour = \"red3\") +\n    ggplot2::ggtitle(label = Title, subtitle = Subtitle) +\n    ggplot2::xlab(x) + \n    ggplot2::ylab(y) +\n    ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5, size = 10, face = \"bold\"), \n                   plot.subtitle = ggplot2::element_text(hjust = 0.5, size = 8))\n  return(p)\n}\n\nls <- vector(\"list\", 4)\nnames(ls) <- c(\"Agriculture\", \"Education\", \"Catholic\", \"Infant.Mortality\")\nfor (i in 1:length(ls)) {\n  ls[[i]] <- regr_p(swiss, names(ls[i]), \"Fertility\")\n}\n\n(ls[[1]] + ls[[2]]) / (ls[[3]] + ls[[4]])\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nFirst thing to notice is the presence of some 'lonely' outliers that may heavily influence some of the estimates (especially in the 'Education' and 'Catholic' models). We'll address these outliers later. Except for the outliers, though, the linear model seems like a decent fit for all the four models. In particular, the 'Education' one has a relatively high *R^2^* (0.4406), and a clear descending pattern. This result is in accordance with most modern fertility studies that confirm the existence of a negative correlation between fertility rates and education status. For example see [Women's education and fertility: results from 26 Demographic and Health Surveys](https://pubmed.ncbi.nlm.nih.gov/7482677/). The 'Agriculture' model also exhibits a clear linear ascending pattern, regardless of the low *R^2^*. The other two models require further investigations. Anyway, empirical data confirms the existence of a positive correlation between fertility and religiosity (see [Human fertility in relation to education, economy, religion, contraception, and family planning programs](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-020-8331-7)), and between fertility and infant mortality (see [The influence of infant and child mortality on fertility in selected countries of the Asian and Pacific region](https://pubmed.ncbi.nlm.nih.gov/12314064/)), as wee see in the respective plots.\n:::\n\n## Diagnostics with lindia\n\n::: justify\n`lindia` provides a set of streamlined functions that allow easy generation of linear regression diagnostic plots necessary for checking linear model assumptions. This package is meant for easy scheming of linear regression diagnostics, while preserving merits of \"The Grammar of Graphics\" as implemented in `ggplot2`.\n\nThe main function of `lindia` package is `lindia::gg_diagnose()` , which outputs an arranged grid of all the diagnostics plots available in `lindia` .\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::gg_diagnose(model)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nAs you can see, the output includes:\n\n-   Histogram of residuals.\n-   Residuals vs. predictors plots.\n-   Residual vs. fit plots.\n-   QQ-plot.\n-   Scale-location plot.\n-   Residual vs leverage plot.\n-   Cook's distance plot.\n\nYou can also add a boxcox plot to the grid, by adding `boxcox=T` parameter to the function call. If you need more flexibility in determining graphical elements and inclusion/exclusion of certain plots, set `plot.all=F` parameter in the function call. It will return a list of all plots, which the user can manipulate.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl <- lindia::gg_diagnose(model, plot.all = F)\nnames(l)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"residual_hist\"    \"Agriculture\"      \"Education\"        \"Catholic\"        \n [5] \"Infant.Mortality\" \"res_fitted\"       \"qqplot\"           \"scalelocation\"   \n [9] \"resleverage\"      \"cooksd\"          \n```\n:::\n:::\n\n\n::: justify\nYou can draw all the plots in a list with `lindia::plot_all()` function. For example, with the following code, we draw all the plots in 'l' list, except for residuals vs predictors plots.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::plot_all(l[-c(2:5)])\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nYou can also draw the plots individually, via the corresponding functions:\n\n-   `gg_reshist()`.\n-   `gg_resfitted()`.\n-   `gg_resX()`.\n-   `gg_qqplot()`.\n-   `gg_boxcox()`.\n-   `gg_scalelocation()`.\n-   `gg_resleverage()`.\n-   `gg_cooksd()`.\n\nFor example, you can draw the histogram of residuals with `lindia::gg_reshist()` .\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::gg_reshist(model)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nAll graphical styles returned by `lindia` graphing function can be overwritten by a call to `ggplot::theme()` (except `lindia::gg_resX()` and `lindia::gg_diagnose()`, which would return a list rather than a single ggplot object). For example:\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::gg_reshist(model) + ggplot2::theme_dark()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-13-1.png){width=100% height=250%}\n:::\n:::\n\n\n## Test linearity assumption\n\n::: justify\nThe easiest and most used method to assess if the linearity assumption holds is through **residual plots** (i.e. residuals vs fitted and residuals vs predictors plots). If the plots exhibit a clear non linear pattern, then the assumption of linearity is violated. It's also important to check for outliers, since the OLS method is sensitive to them. Let's take a closer look at the residuals plots of our swiss model.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::plot_all(l[c(2:6)])\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nLinearity seems to hold reasonably well in 'Agriculture', 'Infant.Mortality'. The points are randomly dispersed around the horizontal lines and don't exhibit clear non linear patterns. Except for a weird pattern in the middle, also 'Catholic' plot exhibits a somewhat linear pattern. 'Education' plot has an extreme outlier, but seems to follow a linear trend too. Looking at the 'Fitted values' plots we also see a clear horizontal pattern, thus the linear model is a good fit overall. The linearity assumption holds reasonably well, here.\n:::\n\n## Test for null residuals mean\n\n::: justify\nThe points in the residuals plots are clearly centered around 0, so it's safe to assume the assumption holds. Anyway we can compute the actual mean for an additional proof.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel$residuals |> mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3.76029e-16\n```\n:::\n:::\n\n\n::: justify\nAs you can see, the mean is so close to 0 that it's practically null.\n:::\n\n## Test if predictors are correlated with residuals\n\n::: justify\nThe residual plots already show there's no clear correlation between residuals and predictors, but we can do an additional check with a correlation matrix. We can plot a nice correlation matrix with `corrplot::corrplot()` function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata.frame(resid = model$residuals, swiss[,-c(1,3)]) |> \n  cor() |> \n  corrplot::corrplot(method = \"number\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nAs you can see, the correlations between residuals and predictors are practically null, thus the assumption holds.\n:::\n\n## Test homoskedasticity assumption\n\n::: justify\nThe residuals vs fitted plot is also a good tool to test for homoskedasticity, together with scale-location plot, which is an even better alternative when testing specifically for homoskedasticity.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::plot_all(l[c(6,8)], ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nThere's no evident fan/conic shape in the first plot. The scale-location plot shows an approximately horizontal pattern (the plot is quite squeezed here), but is heavily influenced by a single outlier in the far left of the plot. Further investigation is needed. To get more info, we can run a formal heteroskedasticity test, like Breusch-Pagan test. If the p-value is less than the significance level, then the null hypotesis of homoskedasticity is rejected. You can run a BP test in R with `car::ncvTest()` function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncar::ncvTest(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNon-constant Variance Score Test \nVariance formula: ~ fitted.values \nChisquare = 0.4687214, Df = 1, p = 0.49358\n```\n:::\n:::\n\n\n::: justify\np \\> 0.05, so we can't reject the null hypotesis of homoskedasticity. Based on the previous tests, we can assume the homoskedasticity assumption actually holds.\n:::\n\n## Test no perfect multicollinearity assumption\n\n::: justify\nThe presence of multicollinearity can be assessed by checking the correlation between predictors, and/or by computing the [Variance Inflation Factor (VIF)](https://corporatefinanceinstitute.com/resources/data-science/variance-inflation-factor-vif/) for each predictor. We already plotted a correlation matrix above; there's a quite high correlation between 'Education' and 'Agriculture' variables. It makes sense that an higher percentual of individuals working in agriculture is tied to a lower education overall. So let's see if the VIFs also suggest the presence of multicollinearity. We can compute the VIFs and associated tolerance values with `olsrr::ols_vif_tol()` function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nolsrr::ols_vif_tol(model)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Variables\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Tolerance\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"VIF\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Agriculture\",\"2\":\"0.4657331\",\"3\":\"2.147153\"},{\"1\":\"Education\",\"2\":\"0.5505512\",\"3\":\"1.816361\"},{\"1\":\"Catholic\",\"2\":\"0.7692805\",\"3\":\"1.299916\"},{\"1\":\"Infant.Mortality\",\"2\":\"0.9029118\",\"3\":\"1.107528\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: justify\n'Agriculture' variable actually has the highest VIF value, but since all VIFs are lower than 3, and all tolerance values are higher then 0.25 (those thresholds are the most commonly used ones, but they might vary a bit depending on how sensitive you want your multicollinearity test to be), we can exclude the presence of multicollinearity.\n:::\n\n## Test normality of residuals assumption\n\n::: justify\nThe easiest and most reliable way to test the normality assumption is by looking and the histogram of residuals and QQ plot.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlindia::plot_all(l[c(1,7)], ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nThe standardized residuals seem to follow the normal distribution reasonably well here. For a more detailed qq plot, with a confidence interval included, you can use functions from other packages, like `car::qqPlot()` .\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqq <- car::qqPlot(model$residuals, id=F)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-21-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nMost observations fall inside the confidence interval, thus we can assume the normality assumption holds.\n:::\n\n## Check for outliers and influential observations\n\n::: justify\nPreviously, we observed some extreme data points that may negatively influence our model. The check for highly influential values, we can look at the residuals vs. leverage plot, and at the Cook's distance plot.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_all(l[c(9,10)], ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=100% height=250%}\n:::\n:::\n\n\n::: justify\nBoth plots show highly influential data points, that when removed from the model, might greatly affect the parameters estimates. As we can see, there are at least 2 observations with high leverage, compared to other data points, and 3 observations (marked with the corresponding indexes) higher then the threshold level in the Cook's plot. Let's take a closer look at these data points.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswiss[c(6,37,47),-3]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Fertility\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Agriculture\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Education\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"Catholic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Infant.Mortality\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"76.1\",\"2\":\"35.3\",\"3\":\"7\",\"4\":\"90.57\",\"5\":\"26.6\",\"_rn_\":\"Porrentruy\"},{\"1\":\"92.2\",\"2\":\"84.6\",\"3\":\"3\",\"4\":\"99.46\",\"5\":\"16.3\",\"_rn_\":\"Sierre\"},{\"1\":\"42.8\",\"2\":\"27.7\",\"3\":\"29\",\"4\":\"58.33\",\"5\":\"19.3\",\"_rn_\":\"Rive Gauche\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n::: justify\n'Porrentruy' has a relatively low 'Fertility' for such high 'Infant.Mortality'. The other two data points seem coherent with our previous model.\n\nGenerally speaking, arbitrarily removing data points is not good practice. Anyway, let's try to re-build the model without these 3 observations, in order to see how influencial they are.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(Fertility ~ Agriculture + Education + Catholic + Infant.Mortality, data = swiss[-c(6,37,47),])\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Fertility ~ Agriculture + Education + Catholic + \n    Infant.Mortality, data = swiss[-c(6, 37, 47), ])\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.9764  -4.7365   0.7061   3.7102  12.5382 \n\nCoefficients:\n                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)      55.67762    8.09634   6.877 3.16e-08 ***\nAgriculture      -0.20119    0.05787  -3.477  0.00126 ** \nEducation        -0.94425    0.12679  -7.447 5.25e-09 ***\nCatholic          0.13174    0.02494   5.283 5.11e-06 ***\nInfant.Mortality  1.50098    0.33565   4.472 6.52e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 5.925 on 39 degrees of freedom\nMultiple R-squared:  0.7683,\tAdjusted R-squared:  0.7445 \nF-statistic: 32.32 on 4 and 39 DF,  p-value: 6.619e-12\n```\n:::\n:::\n\n\n::: justify\nThe 3 data points were actually very influencial. This new model is significantly more accurate, with higher *R^2^* and lower p-values (especially the 'Agriculture' and 'Infant.Mortality' ones got way lower).\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}